

defaults: &defaults

development:
  <<: *defaults
  domain: http://192.168.31.205:8080

test:
  <<: *defaults
  domain: http://192.168.31.205:8080

production:
  <<: *defaults
  domain: http://192.168.31.100